### ISSUE TITLE
Failure to run validation java application

### ISSUE THREAD

**Issue by sneumann** [berlinguyinca/spectra-hash#21]
Hi, after fixing #20 by moving to a non-paranoid network, 
I fail to run the validator on 

````
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
````

Any ideas what to check next appreciated.

Yours,
Steffen

P.S.: Error message is longer than the python implementation :-)

````
sneumann@acryl ~/src/spectra-hash (master) $ java -jar validation/target/validation-1.6.jar 
12:37:40,531 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:37:40,532 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:37:40,532 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/sneumann/src/spectra-hash/validation/target/validation-1.6.jar!/logback.xml]
12:37:40,552 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@c572a80 - URL [jar:file:/home/sneumann/src/spectra-hash/validation/target/validation-1.6.jar!/logback.xml] is not of type file
12:37:40,614 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
12:37:40,643 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
12:37:40,648 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
12:37:40,696 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:37:40,746 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@ba67c2a - There is no conversion class registered for conversion word [wex]
12:37:40,746 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@ba67c2a - [wex] is not a valid conversion word
12:37:40,791 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@2b5273fc - No compression will be used
12:37:40,805 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /tmp/spring.log
12:37:40,805 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/tmp/spring.log]
12:37:40,807 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
12:37:40,807 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
12:37:40,808 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:37:40,809 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1bcc4968 - Registering current configuration as safe fallback point

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.pattern.parser.Compiler@778e2ded - There is no conversion class registered for conversion word [wex]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@778e2ded - [wex] is not a valid conversion word
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:151)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:195)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:64)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:49)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:301)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:253)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:225)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:201)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
	at edu.ucdavis.fiehnlab.spectra.hash.core.validation.Application.main(Application.java:21)
	... 6 more
````

**Comment by sneumann** [comment]
Got it to work on a different computer. WorksForMe.
